[storagebox]
type = sftp
host = u586529.your-storagebox.de
user = u586529
port = 23
key_file = ~/.ssh/id_ed25519
shell_type = unix
known_hosts_file = ~/.ssh/known_hosts
md5sum_command = md5 -r
sha1sum_command = sha1 -r
